### PR TITLE
Add corresponding tags to the protobuf model

### PR DESCRIPTION
**Pull request by lindseydew**
## What does this change?
This adds a field `correspondingTags` to the `Card` protobuf message. This is so the native apps developers can translate  the JSON response returned from the `MyGuardian Feed` endpoint into a protobuf object using this field. This is whilst the API is in a transition to migrate from using a JSON response to a protobuf response.

### CODE REVIEW

**Review by tkgnm — APPROVED** [review]
Looks good!

**Comment by lindseydew** [comment]
> I wonder if this should live at the `BlueprintCard` level rather than article - since this will affect card UI? For context, the iOS app uses the `BlueprintCard` model for rendering the card view @lindseydew @tkgnm

Yeah we can do that. Moved in the next commit

**Comment by aoifemcl15** [comment]
> ## What does this change?
> This adds a field `correspondingTags` to the `Article` protobuf message. This is so the native apps developers can translate the JSON response returned from the `MyGuardian Feed` endpoint into a protobuf object using this field. This is whilst the API is in a transition to migrate from using a JSON response to a protobuf response.

Ignore me - looking at the code changes, it is at the card level already. LGTM 👍

**Comment by aoifemcl15** [comment]
> > I wonder if this should live at the `BlueprintCard` level rather than article - since this will affect card UI? For context, the iOS app uses the `BlueprintCard` model for rendering the card view @lindseydew @tkgnm
> 
> Yeah we can do that. Moved in the next commit

Thanks @lindseydew - LGTM 👍

**Pull request merged**
